### ISSUE TITLE
Error every time I finish a card

### ISSUE THREAD

**Issue by huachuman** [RuzuStudios/ruzu-anki-pop-ups#10]
Whenever I click the Easy Medium Hard etc. buttons I get this error:

Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.25231
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-10 14:47:24

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 127, in wrapped_done
  File "aqt.reviewer", line 465, in after_answer
  File "aqt.reviewer", line 479, in _after_answering
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by huachuman** [comment]
sorry I thought this was the main ruzu repo I didn't realize it was the chrome extension
